/* ==================================================================
   01_create_tables.sql
   Creates the six tables of UniversityDB.

   Demonstrates the Week 1 topics from the training document:
     - What is a Table & Column / Rows & Columns
     - Different Data Types
     - Different types of Keys  (primary, foreign, composite, unique)
     - Referential Integrity    (FOREIGN KEY constraints)

   Tables are dropped in reverse dependency order so that a child table
   never blocks the drop of its parent.
   ================================================================== */

USE UniversityDB;
GO

/* ---------- Clean slate -------------------------------------------
   Enrollments and SemesterFees reference Students and Courses, so they
   must be dropped before the tables they point at. Courses references
   itself (PrerequisiteCourseID), which SQL Server handles on DROP. */
DROP TABLE IF EXISTS Enrollments;
DROP TABLE IF EXISTS SemesterFees;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Instructors;
DROP TABLE IF EXISTS Departments;
GO


/* ---------- 1. Departments ----------------------------------------
   The parent of everything else. No foreign keys of its own.
   DepartmentID is a SURROGATE key: a meaningless number generated by
   the database. DepartmentName is a CANDIDATE key: it is also unique
   and could have served as the primary key. */
CREATE TABLE Departments
(
    DepartmentID    INT             NOT NULL,   -- primary key, assigned by us
    DepartmentName  VARCHAR(60)     NOT NULL,   -- variable-length text, max 60 chars
    Building        VARCHAR(40)     NULL,       -- NULL allowed: may be unassigned
    EstablishedYear SMALLINT        NOT NULL,   -- SMALLINT is plenty for a year

    CONSTRAINT PK_Departments        PRIMARY KEY (DepartmentID),
    CONSTRAINT UQ_Departments_Name   UNIQUE      (DepartmentName),
    -- A CHECK constraint is domain integrity: it restricts the values allowed.
    CONSTRAINT CK_Departments_Year   CHECK (EstablishedYear BETWEEN 1800 AND 2100)
);
GO


/* ---------- 2. Instructors ----------------------------------------
   Each instructor belongs to exactly one department (one-to-many).
   The FOREIGN KEY is what enforces referential integrity: you cannot
   insert an instructor into a department that does not exist. */
CREATE TABLE Instructors
(
    InstructorID    INT             NOT NULL,
    FirstName       VARCHAR(30)     NOT NULL,
    LastName        VARCHAR(30)     NOT NULL,
    Email           VARCHAR(80)     NOT NULL,
    DepartmentID    INT             NOT NULL,   -- foreign key to Departments
    HireDate        DATE            NOT NULL,   -- DATE stores no time component
    Salary          DECIMAL(10, 2)  NOT NULL,   -- exact money value, 2 decimals

    CONSTRAINT PK_Instructors        PRIMARY KEY (InstructorID),
    CONSTRAINT UQ_Instructors_Email  UNIQUE      (Email),
    CONSTRAINT FK_Instructors_Dept   FOREIGN KEY (DepartmentID)
        REFERENCES Departments (DepartmentID),
    CONSTRAINT CK_Instructors_Salary CHECK (Salary > 0)
);
GO


/* ---------- 3. Students -------------------------------------------
   Each student declares one department as their major. */
CREATE TABLE Students
(
    StudentID       INT             NOT NULL,
    FirstName       VARCHAR(30)     NOT NULL,
    LastName        VARCHAR(30)     NOT NULL,
    Email           VARCHAR(80)     NOT NULL,
    DateOfBirth     DATE            NOT NULL,
    EnrollmentDate  DATE            NOT NULL,
    DepartmentID    INT             NOT NULL,   -- foreign key to Departments
    City            VARCHAR(40)     NULL,
    State           CHAR(2)         NULL,       -- CHAR is fixed width: always 2 chars

    CONSTRAINT PK_Students           PRIMARY KEY (StudentID),
    CONSTRAINT UQ_Students_Email     UNIQUE      (Email),
    CONSTRAINT FK_Students_Dept      FOREIGN KEY (DepartmentID)
        REFERENCES Departments (DepartmentID),
    -- A student cannot enrol before they were born.
    CONSTRAINT CK_Students_Dates     CHECK (EnrollmentDate > DateOfBirth)
);
GO


/* ---------- 4. Courses --------------------------------------------
   Two ordinary foreign keys (department, instructor) plus a
   SELF-REFERENCING foreign key: PrerequisiteCourseID points back at
   Courses. That single column is what makes the prerequisite chain in
   Week 7 (recursive query) possible.

   PrerequisiteCourseID is NULLable because an entry-level course has
   no prerequisite. */
CREATE TABLE Courses
(
    CourseID            INT          NOT NULL,
    CourseCode          VARCHAR(10)  NOT NULL,  -- natural key, e.g. 'CS101'
    CourseName          VARCHAR(80)  NOT NULL,
    Credits             TINYINT      NOT NULL,  -- TINYINT holds 0-255
    DepartmentID        INT          NOT NULL,
    InstructorID        INT          NULL,      -- NULL = not yet assigned
    PrerequisiteCourseID INT         NULL,      -- self-reference

    CONSTRAINT PK_Courses            PRIMARY KEY (CourseID),
    CONSTRAINT UQ_Courses_Code       UNIQUE      (CourseCode),
    CONSTRAINT FK_Courses_Dept       FOREIGN KEY (DepartmentID)
        REFERENCES Departments (DepartmentID),
    CONSTRAINT FK_Courses_Instructor FOREIGN KEY (InstructorID)
        REFERENCES Instructors (InstructorID),
    CONSTRAINT FK_Courses_Prereq     FOREIGN KEY (PrerequisiteCourseID)
        REFERENCES Courses (CourseID),
    CONSTRAINT CK_Courses_Credits    CHECK (Credits BETWEEN 1 AND 6),
    -- A course cannot be its own prerequisite.
    CONSTRAINT CK_Courses_NoSelfPrereq CHECK (PrerequisiteCourseID <> CourseID)
);
GO


/* ---------- 5. Enrollments ----------------------------------------
   The bridge (junction) table that resolves the many-to-many relation
   between Students and Courses: one student takes many courses, one
   course is taken by many students.

   EnrollmentID is a surrogate primary key. The UNIQUE constraint on
   (StudentID, CourseID, Semester, AcademicYear) is a COMPOSITE key: it
   stops the same student registering twice for the same course in the
   same term. */
CREATE TABLE Enrollments
(
    EnrollmentID    INT             NOT NULL,
    StudentID       INT             NOT NULL,
    CourseID        INT             NOT NULL,
    Semester        VARCHAR(6)      NOT NULL,   -- 'Fall' or 'Spring'
    AcademicYear    SMALLINT        NOT NULL,
    Grade           CHAR(2)         NULL,       -- NULL until the term is graded
    GradePoints     DECIMAL(3, 2)   NULL,       -- 0.00 to 4.00

    CONSTRAINT PK_Enrollments        PRIMARY KEY (EnrollmentID),
    CONSTRAINT FK_Enrollments_Student FOREIGN KEY (StudentID)
        REFERENCES Students (StudentID),
    CONSTRAINT FK_Enrollments_Course FOREIGN KEY (CourseID)
        REFERENCES Courses (CourseID),
    CONSTRAINT UQ_Enrollments_Once   UNIQUE
        (StudentID, CourseID, Semester, AcademicYear),
    CONSTRAINT CK_Enrollments_Sem    CHECK (Semester IN ('Fall', 'Spring')),
    CONSTRAINT CK_Enrollments_Points CHECK (GradePoints BETWEEN 0.00 AND 4.00)
);
GO


/* ---------- 6. SemesterFees ---------------------------------------
   Money owed and paid per student per term. Gives us clean numeric
   columns for the aggregate work in Week 5 and the PIVOT in Week 6. */
CREATE TABLE SemesterFees
(
    FeeID           INT             NOT NULL,
    StudentID       INT             NOT NULL,
    Semester        VARCHAR(6)      NOT NULL,
    AcademicYear    SMALLINT        NOT NULL,
    AmountDue       DECIMAL(9, 2)   NOT NULL,
    AmountPaid      DECIMAL(9, 2)   NOT NULL,
    DueDate         DATE            NOT NULL,

    CONSTRAINT PK_SemesterFees       PRIMARY KEY (FeeID),
    CONSTRAINT FK_SemesterFees_Stu   FOREIGN KEY (StudentID)
        REFERENCES Students (StudentID),
    CONSTRAINT UQ_SemesterFees_Term  UNIQUE (StudentID, Semester, AcademicYear),
    CONSTRAINT CK_SemesterFees_Due   CHECK (AmountDue >= 0),
    CONSTRAINT CK_SemesterFees_Paid  CHECK (AmountPaid >= 0)
);
GO


/* ---------- Confirm what was built --------------------------------
   sys.tables lists user tables; joining to sys.columns counts columns. */
SELECT
    t.name                        AS TableName,
    COUNT(c.column_id)            AS ColumnCount
FROM sys.tables AS t
INNER JOIN sys.columns AS c ON c.object_id = t.object_id
GROUP BY t.name
ORDER BY t.name;
GO
